tabs:
  main:
    sections:
      -
        fields:
          -
            field:
              type: markdown
              display: Content
              localizable: true
            handle: content
          -
            field:
              type: users
              default: current
              display: Author
              max_items: 1
              localizable: true
            handle: author
          -
            field:
              type: template
              display: Template
              localizable: true
            handle: template
